# Generated by Django 4.2.4 on 2025-04-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qta', '0015_delete_graphics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Support_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_follow_up',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='second_follow_up',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
    ]
